title:            "indoglobal.vlsm.org"
version:          "015---24-Mar-2021"
copyright:        "2021-2021"
description: >- 
  This is indoglobal.vlsm.org!
urlweb:           "https://indoglobal.vlsm.org/"
urlgithub:        "https://github.com/webjekyll/indoglobal/"
urlcontact:       "https://rahmatm.samik-ibrahim.vlsm.org/2021/01/how-to-contact-rahmat-m-samik-ibrahim.html"
author:           "Cecak Bin Kadal"
keywords:         "indoglobal, jekyll, testing"
google_analytics: "UA-89852122-6"
show_downloads:   false
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: URLs
  links:
    - https://https://github.com/rms46/rms46.vlsm.org/
github: [metadata]


